version: '3'

services:
  app-with-help:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "./gofe show-tasks -h"
  app-with-a:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
    command: sh -c "./gofe show-tasks -a -wh"
